from colorama import init, Fore

# colors
BLUE = Fore.BLUE
RED = Fore.RED
GREEN = Fore.GREEN
YELLOW = Fore.YELLOW
CYAN = Fore.CYAN
RESET = Fore.RESET

# messages
DOWNLOAD = GREEN + "[DOWNLOAD]" + RESET
CREATE = GREEN + "[CREATE]" + RESET
UPDATE = GREEN + "[UPDATE]" + RESET
FINISHED = CYAN + "[FINISHED]" + RESET
WARNING = YELLOW + "[WARNING]" + RESET
ERROR = RED + "[ERROR]" + RESET

FILE = Fore.LIGHTCYAN_EX
NUMBER = Fore.LIGHTGREEN_EX
INDEX = Fore.LIGHTMAGENTA_EX
INPUT = Fore.LIGHTMAGENTA_EX

# home directory
HOME = "download"
